szlak, trail 
rzeka, river 
długość, length 
trwania, duration 
śluzy, water gate 
swoboda, freedom 
puszcza, forest 
sprzęt, equipment 
sprzęt komputerowy, hardware
kamień, stone 
dno, bottom 
wymagać, to require 
marzenie, deram
malownicze, picturesque 
wyprawa, expedition 
wycieczki, trip 
bryzg, splash 
wyjątkowy, exceptional 
nienaruszoną, intact 
niezwykłe, unusually 
doświadczenie, experience 
przyjemna, pleasant 
dostępny, available 
początkujących, beginners 
podróży, traveling 
koszt, cost 
kajakiem, kayak 
zł, zloty 
godziny, hours 
otwarcia, opening 
śluz, mucus 
październiku, October 
codziennie, daily 
przewięź, cross 
gorczyca, mustard 
środa, Wednesday 
niedziela, Sunday 
paniewo, panie 
perkuć, Perkuc 
mikaszówka, Mikaszówka 
sosnówek, Sosnówek 
poniedziałek, Monday 
piątek, Friday 
sosnowo, pine 
borki, are 
białobrzegi, Białobrzegi 
tartak, sawmill 
kudrynki, kudrynka 
kurzyniec, Kurzyniec 
zamknięta, closed 
pozostałe, the remaining 
śluzowanie, lockage 
możliwe, possible 
po, after 
wcześniejszym, earlier 
dwudniowym, two -day 
zgłoszeniu, application 
telefonicznym, by phone 
mailowym, e -mail 
zarządu, board 
zlewni, drain 
tel, tel 
email, email 
zzaugustowwodygovpl, zzaugustowwodygovpl 
klasyczny, classic 
powstał, was created 
r, r 
przebiega, runs 
serwy, serves 
przewóz, carriage 
wysokiego, tall 
mostu, bridge 
gawrych, Gawrych 
stary, old 
folwark, grange 
maćkowa, Maciek 
buda, buda 
ruska, Russia 
wysoki, tall 
most, most 
frącki, frile 
jałowy, barren 
róg, corner 
łoski, elbows 
jazy, jazy 
płaska, flat 
wersji, version 
maksymalnej, maximum 
tę, these 
wersję, versions 
powtarzał, he repeated 
karol, karol 
wojtyła, Wojtyła 
go, go 
można, you can 
nazywać, call 
też, also 
papieskim, papal 
supienie, sinking 
filipowska, Filip 
spragnionych, thirsty 
wrażeń, impressions 
miłośników, lovers 
momentami, at times 
zdaje, passes 
rzeką, river 
górską, mountainous 
taki, such 
jej, her 
wysokie, high 
zalesione, forested 
brzegi, edge 
dolnym, lower 
biegu, run 
ma, and 
nizinny, lowland 
zabagnionych, bogged down 
brzegach, edges 
porośniętych, overgrown 
trzciną, cane 
szuwarami, rushes 
kajakarze, canoeists 
mogą, may 
spotkać, meet 
pewne, certain 
utrudnienia, impediments 
jak, how 
przykład, example 
płytkie, shallow 
czy, if 
silny, strong 
prąd, current 
powalone, fallen 
pnie, trunks 
drzew, trees 
bakałarzewie, Bakałarzew 
raczkach, crawl 
małych, small 
trzeba, it's necessary to 
przenieść, move 
kajaki, kayaks 
netty, netty 
malownicza, picturesque 
rzadko, rarely 
uczęszczana, frequented 
nizinna, lowland 
meandrująca, meandering 
wśród, among 
łąk, meadow 
trzcinowisk, reeds 
raczej, rather 
nieznane, unknown 
turystom, tourists 
tereny, areas 
może, maybe 
przedłużeniem, extension 
dwóch, two 
innych, other 
regionu, region 
kierunku, direction 
lipsk, Leipzig 
ruś, rus 
u, in 
ujścia, outlet 
narwi, Narew 
stosunkowo, relatively 
spokojna, calm 
wymarzona, dreamy 
entuzjastów, enthusiasts 
ciszy, silence 
przyrody, nature 
ptactwa, birds 
nizinnym, lowland 
charakterze, character 
licznymi, numerous 
zakolami, soon 
starorzeczami, oxbow lakes 
znajduje, finds 
największy, the biggest 
europie, Europe 
środkowej, middle 
kompleks, complex 
bagien, swamp 
torfowisk, peat bogs 
leży, lies 
obrębie, intercourse 
biebrzańskiego, Biebrzański 
parku, park 
narodowego, national 
wykupienie, redemption 
biletu, ticket 
wstępu, admission 
biwakowanie, camping 
dozwolone, allowed 
miejscach, places 
wyznaczonych, designated 
jezioro, Lake 
dzień, day 
rozpoczyna, begins 
bystrym, Fast 
którym, which 
spływa, flows down 
jeziora, Lakes 
później, later 
staw, joint 
sajownica, Sauline 
przeniesienie, transfer 
wał, shaft 
śluzę, mucus 
